"""node graph edges

C1 of Phase 2: a session stops owning one node and starts owning a DAG.
Autogenerated from ``app/models/tables.py`` and then reworked — see the
comments in :func:`upgrade`, which explain why nothing here rebuilds a table.

**An existing Phase 1 database migrates forward with its history intact.**
There are accepted runs in real databases (`docs/acceptance-phase-1.md`), so
every operation below is one SQLite performs in place:

``ALTER TABLE node ADD COLUMN``
    Natively supported, and supported with ``NOT NULL DEFAULT`` — which is the
    only reason ``touches`` can be non-nullable on a populated table.

``CREATE UNIQUE INDEX ix_node_id_session_id``
    A unique *index*, not a ``UNIQUE`` constraint. SQLite accepts either as the
    parent key of a foreign key, and only the constraint would need the table
    to be dropped, copied and renamed.

That matters beyond losing rows. Batch mode rebuilds a table, and SQLite drops a
table's triggers with it: a ``batch_alter_table("usage_event")`` would silently
take ``usage_event_is_append_only`` with it (revision a83db6150739 says so, and
``tests/storage/test_migrations.py`` fails if it ever happens). This revision
does not touch ``usage_event`` at all, and ``node`` never leaves its place.

Revision ID: dab457c1cd62
Revises: a83db6150739
Create Date: 2026-08-07 10:35:54.053305

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

from app.models.tables import StringTupleType

revision: str = "dab457c1cd62"
down_revision: str | None = "a83db6150739"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Parent key for node_dependency's two composite foreign keys. It has to
    # exist before the table that references it: SQLite reports a missing parent
    # index as "foreign key mismatch" at INSERT time, not at CREATE time, so
    # getting this order wrong fails much later and much less clearly.
    op.create_index("ix_node_id_session_id", "node", ["id", "session_id"], unique=True)

    op.add_column(
        "node",
        sa.Column("touches", StringTupleType(), server_default="[]", nullable=False),
    )
    op.add_column(
        "node",
        sa.Column(
            "estimated_effort", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )

    op.create_table(
        "node_dependency",
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("depends_on_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("created_ms", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "node_id <> depends_on_id",
            name=op.f("ck_node_dependency_no_self_dependency"),
        ),
        # Both endpoints resolve against the *same* session_id column of this
        # row, which is what makes "no edge across sessions" a database fact.
        sa.ForeignKeyConstraint(
            ["depends_on_id", "session_id"],
            ["node.id", "node.session_id"],
            name=op.f("fk_node_dependency_depends_on_id_node"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_id", "session_id"],
            ["node.id", "node.session_id"],
            name=op.f("fk_node_dependency_node_id_node"),
            ondelete="CASCADE",
        ),
        # No duplicate edge, for free and without a second index.
        sa.PrimaryKeyConstraint(
            "node_id", "depends_on_id", name=op.f("pk_node_dependency")
        ),
    )
    op.create_index(
        "ix_node_dependency_depends_on_id", "node_dependency", ["depends_on_id"]
    )
    op.create_index(
        op.f("ix_node_dependency_session_id"), "node_dependency", ["session_id"]
    )


def downgrade() -> None:
    # The edges go first: their foreign keys are the only reason
    # ix_node_id_session_id exists.
    op.drop_index(op.f("ix_node_dependency_session_id"), table_name="node_dependency")
    op.drop_index("ix_node_dependency_depends_on_id", table_name="node_dependency")
    op.drop_table("node_dependency")

    op.drop_index("ix_node_id_session_id", table_name="node")
    # DROP COLUMN is native from SQLite 3.35 and emulated by a rebuild below
    # that; `node` carries no trigger, so the emulation is safe here.
    with op.batch_alter_table("node", schema=None) as batch_op:
        batch_op.drop_column("estimated_effort")
        batch_op.drop_column("touches")
