"""acceptance criteria as an array

`design.md` §8 emits ``acceptance_criteria`` as an array and its
``awaiting_review`` panel shows acceptance-criteria *results*, plural. A single
``TEXT`` column cannot carry a per-criterion pass/fail, and the planner would be
the one joining them — so the loss would happen before anything could object.

Two things the autogenerated version of this revision got wrong, both left as
comments rather than silently fixed, because they are the interesting part:

**It had no data migration.** The column's storage type does not change — a JSON
array still lives in ``TEXT`` — so Alembic saw only a nullability change. But an
existing row holds bare prose, and ``json.loads("pytest passes")`` raises. Every
value has to be rewritten before the column can be read again.

**It rebuilt ``node`` without asking whether that is safe.** ``node`` is the
parent of two foreign keys: ``run.node_id`` and ``node_dependency``'s composite
pair. Batch mode copies the table out and back, and ``migrations/env.py``
already runs with ``PRAGMA foreign_keys=OFF`` for exactly this reason. It is
safe here, but only because ``node`` carries no triggers — revision
``a83db6150739`` documents why the same operation on ``usage_event`` would
silently drop its append-only trigger. ``tests/storage/test_migrations.py``
proves both halves against a populated database.

Revision ID: dab2c49d6ccb
Revises: dab457c1cd62
Create Date: 2026-08-07 11:15:54.884457

"""

import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dab2c49d6ccb"
down_revision: str | None = "dab457c1cd62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id, acceptance_criteria FROM node")).fetchall()

    for node_id, raw in rows:
        # A Phase 1 value is free prose. It becomes exactly *one* criterion:
        # splitting on newlines would be a guess about what the operator meant,
        # and inventing three criteria out of one paragraph is worse than
        # leaving a single one for them to split in the UI. Empty and NULL both
        # mean "no stated criteria".
        criteria = [raw] if raw else []
        bind.execute(
            sa.text("UPDATE node SET acceptance_criteria = :value WHERE id = :id"),
            {"value": json.dumps(criteria, ensure_ascii=False), "id": node_id},
        )

    with op.batch_alter_table("node", schema=None) as batch_op:
        batch_op.alter_column(
            "acceptance_criteria",
            existing_type=sa.VARCHAR(),
            server_default="[]",
            nullable=False,
        )


def downgrade() -> None:
    with op.batch_alter_table("node", schema=None) as batch_op:
        batch_op.alter_column(
            "acceptance_criteria",
            existing_type=sa.VARCHAR(),
            server_default=None,
            nullable=True,
        )

    bind = op.get_bind()
    rows = bind.execute(sa.text("SELECT id, acceptance_criteria FROM node")).fetchall()

    for node_id, raw in rows:
        # Lossy in one direction only: an array of several criteria comes back
        # as newline-joined prose, because that is the only shape the old column
        # had. Downgrading after the planner has written multi-criterion nodes
        # therefore loses the boundaries, not the text.
        criteria = json.loads(raw) if raw else []
        bind.execute(
            sa.text("UPDATE node SET acceptance_criteria = :value WHERE id = :id"),
            {"value": "\n".join(criteria) or None, "id": node_id},
        )
