"""session, node, run, usage_event

The Phase 1 subset of `design.md` §5. Autogenerated from
``app/models/tables.py`` and then reviewed; the one hand-written addition is the
``usage_event`` append-only trigger at the end of :func:`upgrade`, which
autogenerate cannot see.

Revision ID: a83db6150739
Revises:
Create Date: 2026-08-06 20:20:44.583953

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

from app.models.tables import PathType

revision: str = "a83db6150739"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Invariant 4 made structural. A usage row is a projection of one line of
# events.ndjson: if it is wrong, the log is what gets replayed, and a row
# corrected in place is a row the log can no longer explain. Enforced in the
# database rather than only in the repository API because the sqlite3 CLI, a
# future maintenance script, and a well-meaning fix at 2am all bypass Python.
#
# DELETE is deliberately still allowed: ON DELETE CASCADE from `run` is how a
# rebuild discards a whole run projection before re-ingesting it.
#
# Trap for the next migration: a batch_alter_table on `usage_event` rebuilds the
# table, and SQLite drops a table's triggers with it. Alembic will not put this
# back — re-issue it. tests/storage/test_repository.py fails if you forget.
APPEND_ONLY_TRIGGER = "usage_event_is_append_only"

CREATE_APPEND_ONLY_TRIGGER = f"""
CREATE TRIGGER {APPEND_ONLY_TRIGGER}
BEFORE UPDATE ON usage_event
BEGIN
    SELECT RAISE(
        ABORT,
        'usage_event is append-only: replay the run log instead of updating a row'
    );
END
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("repo_path", PathType(), nullable=False),
        sa.Column("workspace_root", PathType(), nullable=False),
        sa.Column(
            "integration_branch", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("auto_merge", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planning", "running", "paused", "done", "failed", name="status_enum"
            ),
            nullable=False,
        ),
        sa.Column("created_ms", sa.Integer(), nullable=False),
        sa.Column("updated_ms", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('planning', 'running', 'paused', 'done', 'failed')",
            name=op.f("ck_session_session_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
    )
    op.create_table(
        "node",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "acceptance_criteria", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("harness", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("worktree_path", PathType(), nullable=True),
        sa.Column("branch", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("base_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "ready",
                "running",
                "awaiting_review",
                "blocked",
                "done",
                "failed",
                "skipped",
                name="status_enum",
            ),
            nullable=False,
        ),
        sa.Column("created_ms", sa.Integer(), nullable=False),
        sa.Column("updated_ms", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('pending', 'ready', 'running', 'awaiting_review', 'blocked', 'done', 'failed', 'skipped')",
            name=op.f("ck_node_node_status"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_node_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_node")),
    )
    with op.batch_alter_table("node", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_node_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "run",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "success",
                "failed",
                "interrupted",
                "budget_exceeded",
                name="status_enum",
            ),
            nullable=False,
        ),
        sa.Column("harness", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cwd", PathType(), nullable=True),
        sa.Column("pid", sa.Integer(), nullable=True),
        sa.Column(
            "harness_session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("harness_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("events_path", PathType(), nullable=False),
        sa.Column("started_ms", sa.Integer(), nullable=True),
        sa.Column("finished_ms", sa.Integer(), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("permission_denial_count", sa.Integer(), nullable=False),
        sa.Column("created_ms", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'failed', 'interrupted', 'budget_exceeded')",
            name=op.f("ck_run_run_state"),
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
            name=op.f("fk_run_node_id_node"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_run_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run")),
        sa.UniqueConstraint("node_id", "attempt", name=op.f("uq_run_node_id_attempt")),
    )
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_node_id"), ["node_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_run_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "usage_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("node_id", sa.String(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("ts", sa.Integer(), nullable=False),
        sa.Column("harness", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("reported", "reconstructed", name="source_enum"),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_5m_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_write_1h_tokens", sa.Integer(), nullable=False),
        sa.Column("price_table_version", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "source IN ('reported', 'reconstructed')",
            name=op.f("ck_usage_event_usage_source"),
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["node.id"],
            name=op.f("fk_usage_event_node_id_node"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["run.id"],
            name=op.f("fk_usage_event_run_id_run"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
            name=op.f("fk_usage_event_session_id_session"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_event")),
        sa.UniqueConstraint("run_id", "seq", name=op.f("uq_usage_event_run_id_seq")),
    )
    with op.batch_alter_table("usage_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usage_event_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index("ix_usage_session_ts", ["session_id", "ts"], unique=False)

    # ### end Alembic commands ###

    op.execute(CREATE_APPEND_ONLY_TRIGGER)


def downgrade() -> None:
    op.execute(f"DROP TRIGGER IF EXISTS {APPEND_ONLY_TRIGGER}")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usage_event", schema=None) as batch_op:
        batch_op.drop_index("ix_usage_session_ts")
        batch_op.drop_index(batch_op.f("ix_usage_event_run_id"))

    op.drop_table("usage_event")
    with op.batch_alter_table("run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_run_session_id"))
        batch_op.drop_index(batch_op.f("ix_run_node_id"))

    op.drop_table("run")
    with op.batch_alter_table("node", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_node_session_id"))

    op.drop_table("node")
    op.drop_table("session")
    # ### end Alembic commands ###
